### PR TITLE
ci: Enable CI on aarch64

### PR DESCRIPTION
**Pull request by chantra**
Signed-off-by: Manu Bretelle <chantr4@gmail.com>

### CODE REVIEW

**Comment by chantra** [comment]
At the time of testing x86_64 with llvm was failing. https://github.com/kernel-patches/vmtest/actions/runs/3423770717 is a run on arm64 only.

**Review by danielocfb — APPROVED** [review]
Looks great to me! Big milestone.

Are these additional test failures (new entries in DENYLIST) understood fully? Should we keep the three column format trying to capture the essence of the problem?

**Comment by chantra** [comment]
> Are these additional test failures (new entries in DENYLIST) understood fully?

No, and they should probably be addressed separately.

> Should we keep the three column format trying to capture the essence of the problem?

The 3 column format is not obvious from the file in this repo. Probably the only place where this is made more obvious is https://github.com/kernel-patches/bpf/blob/bpf-next/tools/testing/selftests/bpf/DENYLIST.s390x . Files should probably have a header explaining the format. This can go in a separate diff.

**Comment by chantra** [comment]
I will land this for now.  kernel-patches/vmtest#169  for file format.

**Pull request merged**
